#!/usr/bin/env node
/**
 * export-verified-mappings.mts
 * ============================
 * Exports human-verified candidates to TypeScript mapping files.
 *
 * SAFETY RULES:
 * - Only exports candidates with humanVerified: true
 * - Never sets humanVerified=true programmatically
 * - Never overwrites existing human-confirmed mappings
 * - Never copies mappings between fonts
 *
 * Usage:
 *   npx tsx scripts/export-verified-mappings.mts KAP112
 *   npx tsx scripts/export-verified-mappings.mts --all
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from "node:fs";
import path from "node:path";

const ROOT = path.resolve(new URL("..", import.meta.url).pathname);
const CANDIDATES_DIR = path.join(ROOT, "mapping-data", "candidates");
const VERIFIED_DIR = path.join(ROOT, "mapping-data", "verified");
const MAPPINGS_DIR = path.join(ROOT, "src", "converter", "mappings");
const GLYPH_DATASET_DIR = path.join(ROOT, "mapping-data", "glyph-dataset");

/** Auto-detect fonts from glyph-dataset directories (single source of truth). */
function detectFonts(): string[] {
  if (!existsSync(GLYPH_DATASET_DIR)) return [];
  return readdirSync(GLYPH_DATASET_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory() && /^KAP\d+$/.test(d.name))
    .map((d) => d.name)
    .sort();
}

const KAP_FONTS = detectFonts() as readonly string[];
type KapFont = (typeof KAP_FONTS)[number];

interface MappingCandidate {
  font: KapFont;
  byte: number;
  hex: string;
  unicode: string;
  kap?: string;
  confidence: number;
  confidenceCategory: string;
  status: string;
  humanVerified: boolean;
  reasoning: string;
  generatedAt: string;
  updatedAt: string;
  metadata?: Record<string, unknown>;
}

interface CandidateFile {
  font: KapFont;
  generatedAt: string;
  provider: string;
  candidates: MappingCandidate[];
}

interface VerifiedFile {
  font: KapFont;
  verifiedAt: string;
  verifiedBy: string;
  mappings: Array<{
    font: KapFont;
    byte: number;
    hex: string;
    unicode: string;
    kap?: string;
    verifiedAt: string;
    verifiedBy: string;
    source: "human" | "ai_confirmed";
    confidence: number;
  }>;
}

interface ConversionRule {
  unicode: string;
  kap: string;
}

interface VerifiedSample {
  unicode: string;
  expected: string;
  source: string;
}

function loadCandidateFile(font: KapFont): CandidateFile | null {
  const filePath = path.join(CANDIDATES_DIR, `${font.toLowerCase()}-candidates.json`);
  if (!existsSync(filePath)) {
    return null;
  }
  return JSON.parse(readFileSync(filePath, "utf8"));
}

function loadVerifiedFile(font: KapFont): VerifiedFile | null {
  const filePath = path.join(VERIFIED_DIR, `${font.toLowerCase()}-verified.json`);
  if (!existsSync(filePath)) {
    return null;
  }
  return JSON.parse(readFileSync(filePath, "utf8"));
}

function saveVerifiedFile(font: KapFont, data: VerifiedFile): void {
  mkdirSync(VERIFIED_DIR, { recursive: true });
  const filePath = path.join(VERIFIED_DIR, `${font.toLowerCase()}-verified.json`);
  writeFileSync(filePath, JSON.stringify(data, null, 2));
}

function generateMappingModule(
  font: KapFont,
  rules: ConversionRule[],
  samples: VerifiedSample[]
): string {
  const fontLower = font.toLowerCase();
  const rulesVar = `${font.toUpperCase()}_RULES`;
  const samplesVar = `${font.toUpperCase()}_SAMPLES`;

  const rulesStr = rules
    .map((r) => `  { unicode: ${JSON.stringify(r.unicode)}, kap: ${JSON.stringify(r.kap)} }`)
    .join(",\n");

  const samplesStr = samples
    .map(
      (s) =>
        `  {\n    unicode: ${JSON.stringify(s.unicode)},\n    expected: ${JSON.stringify(s.expected)},\n    source: ${JSON.stringify(s.source)},\n  }`
    )
    .join(",\n");

  return `import type { ConversionRule, VerifiedSample } from "../types";

/**
 * ${font} — Unicode -> legacy mapping table.
 *
 * STATUS: PARTIALLY VERIFIED (AI-generated, human-confirmed).
 *
 * This mapping was generated by the AI-assisted KAP Mapping Analyzer
 * and confirmed by human review. The full table must still be supplied
 * before conversion is enabled.
 *
 * SAFETY: This file must NOT be modified by AI scripts directly.
 * Only human-confirmed mappings should be added here.
 */

export const ${rulesVar}: ConversionRule[] = [
${rulesStr}
];

export const ${samplesVar}: VerifiedSample[] = [
${samplesStr}
];
`;
}

function exportFont(font: KapFont): { exported: number; skipped: number } {
  console.log(`\nExporting verified mappings for ${font}...`);

  // Load candidate file
  const candidateFile = loadCandidateFile(font);
  if (!candidateFile) {
    console.log(`  No candidate file found for ${font}`);
    return { exported: 0, skipped: 0 };
  }

  // Load existing verified file
  const verifiedFile = loadVerifiedFile(font);

  // Filter to only human-verified candidates
  const verifiedCandidates = candidateFile.candidates.filter(
    (c) => c.humanVerified && c.status === "confirmed"
  );

  if (verifiedCandidates.length === 0) {
    console.log(`  No verified candidates for ${font}`);
    return { exported: 0, skipped: 0 };
  }

  // Merge with existing verified mappings
  const existingMappings = new Map<number, VerifiedFile["mappings"][0]>();
  if (verifiedFile) {
    for (const m of verifiedFile.mappings) {
      existingMappings.set(m.byte, m);
    }
  }

  // Add new verified candidates
  let newCount = 0;
  for (const candidate of verifiedCandidates) {
    if (!existingMappings.has(candidate.byte)) {
      existingMappings.set(candidate.byte, {
        font,
        byte: candidate.byte,
        hex: candidate.hex,
        unicode: candidate.unicode,
        kap: candidate.kap,
        verifiedAt: new Date().toISOString(),
        verifiedBy: "human",
        source: "ai_confirmed",
        confidence: candidate.confidence,
      });
      newCount++;
    }
  }

  // Save verified file
  const updatedVerifiedFile: VerifiedFile = {
    font,
    verifiedAt: new Date().toISOString(),
    verifiedBy: "human",
    mappings: Array.from(existingMappings.values()).sort(
      (a, b) => a.byte - b.byte
    ),
  };
  saveVerifiedFile(font, updatedVerifiedFile);

  // Generate TypeScript mapping file
  const rules: ConversionRule[] = updatedVerifiedFile.mappings.map((m) => ({
    unicode: m.unicode,
    kap: m.kap ?? String.fromCharCode(m.byte),
  }));

  // Keep existing golden sample
  const samples: VerifiedSample[] = [
    {
      unicode: "ગુજરાતી",
      expected: "VF5[,F",
      source: "Project-origin golden sample from src/App.tsx",
    },
  ];

  const moduleContent = generateMappingModule(font, rules, samples);
  const modulePath = path.join(MAPPINGS_DIR, `${fontLower}.ts`);
  writeFileSync(modulePath, moduleContent);

  console.log(
    `  Exported ${rules.length} rules (${newCount} new) to ${path.relative(ROOT, modulePath)}`
  );

  return { exported: rules.length, skipped: 0 };
}

function main(): number {
  const args = process.argv.slice(2);
  const exportAll = args.includes("--all");
  const fontArg = args.find((a) => !a.startsWith("--"));

  if (!exportAll && !fontArg) {
    console.error("Usage: npx tsx scripts/export-verified-mappings.mts <FONT> | --all");
    process.exit(1);
  }

  const fontsToExport: KapFont[] = exportAll
    ? [...KAP_FONTS]
    : [(fontArg?.toUpperCase() as KapFont) ?? "KAP112"];

  let totalExported = 0;
  let totalSkipped = 0;

  for (const font of fontsToExport) {
    if (!KAP_FONTS.includes(font)) {
      console.error(`Invalid font: ${font}`);
      continue;
    }
    const result = exportFont(font);
    totalExported += result.exported;
    totalSkipped += result.skipped;
  }

  console.log(`\nExport complete: ${totalExported} rules exported`);
  return 0;
}

process.exit(main());
