"""
First-pass byte -> Gujarati element candidates for the KAP legacy fonts,
produced by rendering each byte's glyph and reading it visually (render+vision).

Confidence:
  high = validated (e.g. via the word આપેલા) or an unmistakable letter/symbol
  med  = probable letterform, should be confirmed by a Gujarati reader
  low  = uncertain / matra / precomposed ligature -> needs native-reader ID

kind: consonant | vowel | matra | sign | conjunct | ligature | digit | symbol | punct | unknown

NOTE: These are CANDIDATES ONLY. Nothing here is authoritative. A human who
reads Gujarati must confirm/correct every row before any mapping is trusted.
The four fonts (KAP110/111/112/122) share one byte->glyph layout (verified),
differing only in weight; the worksheet still shows all four so each byte is
confirmed per font (no blind cross-font copying).
"""

# byte: (gujarati_guess, confidence, kind, note)
CAND = {
    0x21: ("૧", "high", "digit", ""),
    0x22: ("",  "low",  "matra", "small curved top-mark"),
    0x23: ("૩", "high", "digit", ""),
    0x24: ("૪", "high", "digit", ""),
    0x25: ("૨", "high", "digit", ""),
    0x26: ("૭", "high", "digit", ""),
    0x27: ("૮", "med",  "digit", "digit 8?"),
    0x28: ("૯", "med",  "digit", "digit 9?"),
    0x29: ("૦", "high", "digit", ""),
    0x2A: ("",  "low",  "unknown", "tick/hook shape"),
    0x2B: ("ત્ર", "low", "conjunct", "conjunct? (tra)"),
    0x2C: ("લ", "high", "consonant", "validated (આપેલા)"),
    0x2D: ("૬", "high", "digit", ""),
    0x2E: ("",  "low",  "unknown", "loop+tail; maybe ઠ or a vowel"),
    0x2F: ("ણ", "low",  "consonant", "loop; maybe ણ/ળ"),
    0x30: ("ડ", "med",  "consonant", ""),
    0x31: ("ક્ષ", "low", "conjunct", "ksa-like; possible dup of 0x6B"),
    0x32: ("દ", "low",  "consonant", "maybe દ"),
    0x33: ("ધ", "low",  "consonant", "maybe ધ; possible dup of 0x57"),
    0x34: ("",  "low",  "sign", "small diacritic top-right"),
    0x35: ("પ", "high", "consonant", "validated (આપેલા)"),
    0x36: ("ણ", "med",  "consonant", ""),
    0x37: ("જ્ઞ", "low", "conjunct", "gnya-like; or ઞ"),
    0x38: ("ટ", "med",  "consonant", "compare 0x77"),
    0x39: ("ઠ", "med",  "consonant", ""),
    0x3A: ("સ", "med",  "consonant", "compare 0x3B"),
    0x3B: ("સ", "low",  "consonant", "looks like સ; possible dup of 0x3A"),
    0x3C: ("",  "low",  "matra", "horizontal bar; matra/virama?"),
    0x3D: ("",  "low",  "sign", "small caret ^"),
    0x3E: ("ઈ", "med",  "vowel", ""),
    0x3F: ("ઈ", "low",  "vowel", "maybe ઈ/એ"),
    0x40: ("ક", "high", "consonant", "validated"),
    0x41: ("બ", "high", "consonant", "validated"),
    0x42: ("ખ", "high", "consonant", "validated"),
    0x43: ("હ", "med",  "consonant", ""),
    0x44: ("મ", "high", "consonant", "validated"),
    0x45: ("ભ", "high", "consonant", "validated"),
    0x46: ("ા", "high", "matra", "aa-matra (kaano); validated"),
    0x47: ("ન", "high", "consonant", "validated"),
    0x48: ("જ", "med",  "consonant", ""),
    0x49: ("ય", "med",  "consonant", ""),
    0x4A: ("વ", "med",  "consonant", "compare 0xFD"),
    0x4B: ("છ", "high", "consonant", "validated"),
    0x4C: ("ી", "low",  "matra", "tall stroke w/ flag; ii-matra?"),
    0x4D: ("ી", "low",  "matra", "matra?"),
    0x4E: ("ડ", "low",  "consonant", "loop w/ tail; ડ/દ?"),
    0x4F: ("ફ", "high", "consonant", "validated"),
    0x50: ("",  "low",  "sign", "single dot; anusvara?"),
    0x51: ("ષ", "med",  "consonant", "validated batch"),
    0x52: ("ચ", "high", "consonant", "validated"),
    0x53: ("ક", "low",  "consonant", "ka-like; possible dup of 0x40"),
    0x54: ("ત", "high", "consonant", "validated"),
    0x55: ("ગ", "high", "consonant", "validated"),
    0x56: ("અ", "high", "vowel", "validated (આપેલા)"),
    0x57: ("ધ", "med",  "consonant", ""),
    0x58: ("શ", "high", "consonant", "validated"),
    0x59: ("થ", "high", "consonant", "validated"),
    0x5A: ("ર", "med",  "consonant", ""),
    0x5B: ("ે", "high", "matra", "e-matra; validated"),
    0x5C: ("",  "low",  "sign", "small diamond dot"),
    0x5D: ("",  "low",  "matra", "hook; u-matra?"),
    0x5E: ("",  "low",  "unknown", "6-like shape"),
    0x5F: ("ઈ", "low",  "vowel", "loop+dot"),
    0x60: ("ઙ", "low",  "consonant", "nga?"),
    0x61: ("ઉ", "med",  "vowel", ""),
    0x62: ("ઊ", "low",  "vowel", "u/uu"),
    0x63: ("",  "low",  "unknown", "loop+tail"),
    0x64: ("",  "low",  "unknown", "tta+bar; conjunct?"),
    0x65: ("",  "low",  "unknown", "ha-like loop"),
    0x66: ("",  "low",  "punct", "large '(' bracket"),
    0x67: ("",  "low",  "matra", "top hook (reph?)"),
    0x68: ("ઋ", "low",  "vowel", "vocalic R? or conjunct"),
    0x69: ("",  "low",  "matra", "hook; ru-matra?"),
    0x6A: ("",  "low",  "unknown", "hollow circle ○"),
    0x6B: ("ક્ષ", "med", "conjunct", ""),
    0x6C: ("િ", "low",  "matra", "tall bracket; pre-base i-matra?"),
    0x6D: ("",  "low",  "punct", "'?'-shape"),
    0x6E: ("ઘ", "med",  "consonant", ""),
    0x6F: ("ઃ", "med",  "sign", "visarga"),
    0x70: ("",  "low",  "unknown", "loop"),
    0x71: ("",  "low",  "matra", "hook"),
    0x72: ("ર", "low",  "consonant", "2-like; ર?"),
    0x73: ("",  "low",  "punct", "large '(' bracket"),
    0x74: ("",  "low",  "matra", "top hook"),
    0x75: ("",  "low",  "matra", "small hook"),
    0x76: ("",  "low",  "ligature", "tta+matra?"),
    0x77: ("ટ", "med",  "consonant", "compare 0x38"),
    0x78: ("",  "low",  "consonant", "ra/2 variant"),
    0x79: ("",  "low",  "unknown", "loop+tail; 7-like"),
    0x7A: ("શ્ર", "low", "conjunct", "sh-conjunct?"),
    0x7B: ("",  "low",  "matra", "hook+tail"),
    0x7C: ("",  "low",  "sign", "short diagonal stroke"),
    0x7D: ("",  "low",  "matra", "hook (u-matra)"),
    0x7E: ("૩", "low",  "digit", "3-like; possible dup of 0x23"),
    0x82: ("",  "low",  "conjunct", "ka-conjunct (kra/kka)?"),
    0x83: ("",  "low",  "ligature", "consonant+matra"),
    0x84: ("",  "low",  "matra", "hook"),
    0x85: ("અ", "low",  "vowel", "a-like; possible dup of 0x56"),
    0x86: ("",  "low",  "ligature", "ha+u (હુ)?"),
    0x87: ("",  "low",  "ligature", "ha+matra"),
    0x88: ("",  "low",  "ligature", "ha+u (હુ)?"),
    0x89: ("",  "low",  "ligature", "ha+matra"),
    0x8A: ("",  "low",  "ligature", "tta+matra"),
    0x8B: ("",  "low",  "ligature", "tta+u (ટુ)?"),
    0x8C: ("",  "low",  "ligature", "tta+matra"),
    0x91: ("",  "low",  "matra", "top hook"),
    0x92: ("",  "low",  "ligature", "tta+matra"),
    0x93: ("",  "low",  "ligature", "tta+u"),
    0x94: ("",  "low",  "matra", "hook (u)"),
    0x95: ("",  "low",  "ligature", "lla+matra (ળ)"),
    0x96: ("",  "low",  "ligature", "lla+matra"),
    0x97: ("",  "low",  "matra", "pre-base i-matra form (િ)"),
    0x98: ("",  "low",  "matra", "i-matra form"),
    0x99: ("",  "low",  "matra", "i-matra + sign"),
    0x9A: ("",  "low",  "matra", "i-matra + sign"),
    0x9B: ("",  "low",  "matra", "i-matra form (ી)"),
    0x9C: ("",  "low",  "matra", "i-matra + sign"),
    0x9F: ("",  "low",  "matra", "hook"),
    0xA0: ("",  "low",  "matra", "curve"),
    0xA1: ("",  "low",  "matra", "hook+diamond"),
    0xA2: ("",  "low",  "matra", "hook"),
    0xA3: ("",  "low",  "matra", "hook+dot"),
    0xA4: ("",  "low",  "matra", "hook"),
    0xA5: ("",  "low",  "matra", "hook+curve"),
    0xA6: ("",  "low",  "matra", "hook+dot"),
    0xA7: ("૩", "low",  "digit", "3-like"),
    0xA8: ("",  "low",  "matra", "hook"),
    0xA9: ("",  "low",  "matra", "hook+diamond"),
    0xAA: ("",  "low",  "sign", "smile-curve (below-base)"),
    0xAB: ("",  "low",  "sign", "smile-curve+diamond"),
    0xAC: ("",  "low",  "matra", "small hook"),
    0xAD: ("",  "low",  "matra", "hook+diamond"),
    0xAE: ("",  "low",  "matra", "hook"),
    0xAF: ("",  "low",  "matra", "diagonal hook"),
    0xB0: ("",  "low",  "matra", "diagonal hook"),
    0xB1: ("",  "low",  "sign", "short diagonal"),
    0xB2: ("",  "low",  "matra", "curve"),
    0xB3: ("",  "low",  "vowel", "e-ish"),
    0xB4: ("",  "low",  "matra", "hook"),
    0xB5: ("કે", "low", "ligature", "ka+e?"),
    0xB6: ("ખે", "low", "ligature", "kha+e?"),
    0xB7: ("ગે", "low", "ligature", "ga+e?"),
    0xB8: ("ઘે", "low", "ligature", "gha+e?"),
    0xB9: ("",  "low",  "ligature", "consonant+e"),
    0xBA: ("",  "low",  "ligature", "consonant+matra"),
    0xBB: ("",  "low",  "ligature", "vowel+matra"),
    0xBC: ("ઍ", "low",  "vowel", "candra-e?"),
    0xBD: ("",  "low",  "ligature", "consonant+matra"),
    0xBE: ("",  "low",  "ligature", "consonant+matra"),
    0xBF: ("",  "low",  "ligature", "consonant+matra"),
    0xC0: ("",  "low",  "ligature", "consonant+matra"),
    0xC1: ("",  "low",  "ligature", "consonant+matra"),
    0xC2: ("",  "low",  "ligature", "consonant+matra"),
    0xC3: ("",  "low",  "vowel", "8-like loop"),
    0xC4: ("",  "low",  "ligature", "consonant+matra"),
    0xC5: ("ત", "low",  "consonant", "ta-like+matra"),
    0xC6: ("શ્ર", "low", "conjunct", ""),
    0xC7: ("શ્ર", "low", "conjunct", ""),
    0xC8: ("શ્ર", "low", "conjunct", ""),
    0xC9: ("લ", "low",  "ligature", "la+matra"),
    0xCA: ("લ", "low",  "ligature", "la+matra"),
    0xCB: ("લ", "low",  "ligature", "la+matra"),
    0xCC: ("",  "low",  "ligature", "consonant+matra"),
    0xCD: ("",  "low",  "ligature", "consonant+matra"),
    0xCE: ("",  "low",  "ligature", "consonant+matra"),
    0xCF: ("",  "low",  "ligature", "consonant+matra"),
    0xD0: ("ભ", "low",  "ligature", "bha+matra"),
    0xD1: ("ભ", "low",  "ligature", "bha+matra"),
    0xD2: ("મ", "low",  "ligature", "ma+matra"),
    0xD3: ("પ્ર", "low", "conjunct", "pra?"),
    0xD4: ("પ્ર", "low", "conjunct", "pra?"),
    0xD5: ("ચ", "low",  "consonant", "cha+matra"),
    0xD6: ("",  "low",  "ligature", "sha/sa+matra"),
    0xD7: ("",  "low",  "ligature", "sha/sa+matra"),
    0xD8: ("સ", "low",  "conjunct", "sa-conjunct"),
    0xD9: ("સ", "low",  "conjunct", "sa-conjunct"),
    0xDA: ("ર", "low",  "conjunct", "ra-conjunct"),
    0xDB: ("ર", "low",  "conjunct", "ra-conjunct"),
    0xDC: ("",  "low",  "matra", "hook"),
    0xDD: ("",  "low",  "conjunct", "conjunct/vowel"),
    0xDE: ("ળ", "low",  "ligature", "lla/nna+i-matra"),
    0xDF: ("",  "low",  "matra", "top hook"),
    0xE0: ("ત", "low",  "consonant", "ta+matra"),
    0xE1: ("",  "low",  "matra", "bracket >"),
    0xE2: ("",  "low",  "matra", "hook"),
    0xE3: ("ઠ", "low",  "consonant", "loop"),
    0xE4: ("ક્ષ", "low", "conjunct", ""),
    0xE5: ("",  "low",  "matra", "hook"),
    0xE6: ("-", "high", "punct", "hyphen"),
    0xE7: ("—", "high", "punct", "dash"),
    0xE8: ("×", "high", "symbol", ""),
    0xE9: ("%", "high", "symbol", ""),
    0xEA: ("=", "high", "symbol", ""),
    0xEB: ("÷", "high", "symbol", ""),
    0xEC: ("+", "high", "symbol", ""),
    0xED: ("/", "high", "symbol", ""),
    0xEE: (";", "med",  "punct", "semicolon"),
    0xEF: ("‘", "med",  "punct", "left quote"),
    0xF0: ("’", "med",  "punct", "right quote/apostrophe"),
    0xF1: ("★", "high", "symbol", ""),
    0xF2: ("!", "high", "punct", ""),
    0xF3: ("ઇં", "low", "vowel", "i+anusvara"),
    0xF4: ("ઈ", "med",  "vowel", ""),
    0xF5: ("ઉ", "med",  "vowel", ""),
    0xF6: ("ઉં", "low", "vowel", "u+anusvara"),
    0xF7: ("ઊ", "low",  "vowel", "uu"),
    0xF8: ("ૐ", "high", "symbol", "om"),
    0xF9: ("",  "low",  "vowel", "loop+tail"),
    0xFA: ("ઐ", "low",  "vowel", "ai?"),
    0xFB: ("",  "low",  "sign", "raised dot (anusvara?)"),
    0xFC: ("",  "low",  "unknown", "hollow circle"),
    0xFD: ("વ", "med",  "consonant", "compare 0x4A"),
    0xFE: ("",  "low",  "consonant", "ya-like+tail"),
    0xFF: ("ટ", "low",  "consonant", "tta/loop+tail"),
}

NOTDEF = {0x7F, 0x80, 0x81, 0x8D, 0x8E, 0x8F, 0x90, 0x9D, 0x9E}
REAL_BYTES = [b for b in range(0x21, 0x100) if b not in NOTDEF]
